### PR TITLE
Use Context API with Gatsby Plugin React Next and use React Router by defining client side routes.

### PR DESCRIPTION
**Pull request by bzhr**
- All user management routes are pushed under `/app/` and `/app/` is defined as client side route in `gatsby-node.js`, so that the web site can build. 

- `gatsby-plugin-react-next` allows for use of `context` API. 

- Project is restructured such that in pages `/app/` is a gateway to the client side part, while the client side pages like: `SignIn`, `Home` and `Account` are moved to `/componenets`.

### CODE REVIEW

**Comment by rwieruch** [comment]
Nice! 🚀  Only issue is that the branch cannot be merged. Did you add your changes on top of the recent master branch?

**Comment by bzhr** [comment]
Yes, I forked the repo and then created the `auth` branch out of the `master` branch.

**Comment by rwieruch** [comment]
Okay. I was wondering because there are still recent changes from my account in the PR. Either you can create a PR with a new fork or I need to address the conflicts in this PR at some point :D

**Comment by rwieruch** [comment]
This PR https://github.com/rwieruch/gatsby-firebase-authentication/pull/3 should have fixed the issue.

**Pull request closed without merging**
